### ISSUE TITLE
Textdialog not proceeding when clicking on it.

### ISSUE THREAD

**Issue by lcatania** [nkzw-tech/athena-crisis#52] opened 2024-09-13 13:29 UTC
Hey, 

i just started playing the Intro/Tutorial and i play mainly with the mouse. 
Instincivly i click on the dialog box to proceed to the next textdialog while on the top box it works when the textdialog appears at the bottom of the screen i have to click somewhere outside of it to trigger the next dialogbox. This behaviour is a bit annoying and is not consistent :)

**Comment by cpojer** [comment] 2024-09-15 00:23
Duplicate of #54.

**Comment by cpojer** [comment] 2024-09-15 00:33
There is no difference between the dialogue except their position. Clicking or pressing the spacebar both advance the text. If there is still text that hasn't been revealed yet in the current sentence, it completes that first so you have to click twice.

Do you mind recording a video or some other way to show the problem?

**Comment by lcatania** [comment] 2024-09-15 10:31
Here is a video of it :)
https://github.com/user-attachments/assets/ddb0362e-74e4-4b42-b9d8-374142ca25eb

**Comment by cpojer** [comment] 2024-09-15 14:45
lol, turns out document.body is sometimes not tall enough. Thanks for the report, fixed in https://github.com/nkzw-tech/athena-crisis/commit/8ca5acfde8d8bc6789ab5991a2c6b62a58f64f23.

**Closed by cpojer** 2024-09-15 14:45 UTC
