### ISSUE TITLE
Can't access settings without loosing scenario progress

### ISSUE THREAD

**Issue by lcatania** [nkzw-tech/athena-crisis#55] opened 2024-09-14 08:07 UTC
When planning the tutorial I wanted to change the sound volume and after navigating to the settings and going back to the scenario , the state of the tutorial was lost and I had to go through all the dialogs again.

That is very annoying for someone trying to learn the game

**Comment by cpojer** [comment] 2024-09-15 00:23
Duplicate of #54.

**Closed by cpojer** 2024-09-15 00:23 UTC
